aws_account: "354789122408"
aws_region: eu-west-2

domain:
  domain_name: dev.thefilmdb.io

network:
  vpc:
    cidr: 10.50.0.0/16
    create_natgateway: 0

  subnets:
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

compute:
  cognito:
    user_pood_id: us-east-1_qeG3IyrM8
    react_app_client_id: 5jqlpbbhbbti745433fg7vtpa0

  s3:
    blob_bucket: thedb-blob-dev

  ecs:
    enable_auto_shutdown: True
    backend:
      repo_arn: "arn:aws:ecr:us-east-1:384549422462:repository/thedb/api"
      image_tag: "dev-latest"
      port: 8080
      cpu: 256
      memory: 512
      minimum_containers: 0
      maximum_containers: 3
      fargate_spot:
        weight: 100
        base: 1
      fargate:
        weight: 0
        base: 0

    client_webapp:
      repo_arn: "arn:aws:ecr:us-east-1:384549422462:repository/thedb/client_webapp"
      image_tag: "dev-latest"
      port: 80
      cpu: 1024
      memory: 2048
      minimum_containers: 0
      maximum_containers: 3
      fargate_spot:
        weight: 100
        base: 1
      fargate:
        weight: 0
        base: 0
