aws_account: "354789122408"
aws_region: eu-west-2

domain:
  frontend_domain: dev.thefilmdb.io
  backend_domain: api-dev.thefilmdb.io

network:
  vpc:
    cidr: 10.50.0.0/16
    create_natgateway: 0

  subnets:
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

compute:
  ecs:
    backend:
      repo_arn: "arn:aws:ecr:eu-west-2:354789122408:repository/thedb-backend"
      image_tag: "latest"
      cpu: 256
      memory: 512
      minimum_containers: 1
      maximum_containers: 3
      fargate_spot:
        weight: 100
        base: 1
      fargate:
        weight: 0
        base: 0

    client_webapp:
      repo_arn: "arn:aws:ecr:eu-west-2:354789122408:repository/thedb-frontend"
      image_tag: "latest"
      cpu: 1024
      memory: 2048
      minimum_containers: 1
      maximum_containers: 3
      fargate_spot:
        weight: 100
        base: 1
      fargate:
        weight: 0
        base: 0


    redis:
      repo: "redis"
      image_tag: "alpine"
      cpu: 1024
      memory: 2048
      minimum_containers: 1
      maximum_containers: 3
      fargate_spot:
        weight: 100
        base: 1
      fargate:
        weight: 0
        base: 0

    db:
      az: eu-west-2c