aws_account: "354789122408"
aws_region: eu-west-2

domain:
  frontend_domain: thefilmdb.io
  backend_domain: api.thefilmdb.io
  
network:
  vpc:
    cidr: 10.1.0.0/16
    create_natgateway: 1
    natGatewaySubnetName: Public

  subnets:
    # Backend subnet
    - cidrMask: 21
      name: Private
      subnetType: PRIVATE_WITH_EGRESS
    # Client UI subnet
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

compute:
  ecs:
    backend:
      repo_arn: "arn:aws:ecr:eu-west-2:354789122408:repository/thedb-backend"
      image_tag: "latest"
      cpu: 256
      memory: 512
      minimum_containers: 1
      maximum_containers: 3
      fargate_spot:
        weight: 0
        base: 0
      fargate:
        weight: 1
        base: 100

    client_webapp:
      repo_arn: "arn:aws:ecr:eu-west-2:354789122408:repository/thedb-frontend"
      image_tag: "latest"
      cpu: 1024
      memory: 2048
      minimum_containers: 1
      maximum_containers: 3
      fargate_spot:
        weight: 0
        base: 0
      fargate:
        weight: 100
        base: 1
